listen_address: ":9001"

checks:
  public_sites:
    - name: google
      url: https://www.google.com
      expected_status: 200
      timeout: 2s
    - name: example
      url: https://www.sunet.se
      expected_status: 200
      timeout: 1s
  public_sites_1:
    - name: google
      url: https://www.google.com
      expected_status: 200
      timeout: 2s
    - name: example
      url: https://www.sunet.se
      expected_status: 200
      timeout: 1s